"use client"

import { createContext, useContext, useState, useEffect, ReactNode } from "react"

export type Locale = "en" | "fr" | "ar"

interface LanguageContextType {
  locale: Locale
  setLocale: (locale: Locale) => void
  t: (key: string) => string
  dir: "ltr" | "rtl"
  formatNumber: (n: number) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Locale, Record<string, string>> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.search": "Search",
    "nav.notifications": "Notifications",
    "nav.profile": "Profile",

    // Discover
    "discover.browseCategories": "Browse Categories",
    "discover.all": "All",
    "discover.featuredProviders": "Featured Providers",
    "discover.topRated": "Top Rated",
    "discover.viewAll": "View All",
    "discover.seeMore": "See More",
    "discover.noProviders": "No providers found",
    "discover.noProvidersHint": "Try adjusting your search or category filters",
    "discover.searchPlaceholder": "Search doctors, artisans, auto-entrepreneurs...",
    "discover.reviews": "reviews",

    // Categories
    "regulated_profession": "Regulated Liberal Professions",
    "artisan": "Artisans & Technical Trades",
    "auto_entrepreneur": "Auto-Entrepreneurs",

    // App name
    "app.name": "Qantara",

    // Provider Details
    "provider.about": "About",
    "provider.selectService": "Select a Service",
    "provider.selectDateTime": "Select Date & Time",
    "provider.availableTimes": "Available times for",
    "provider.reviews": "Reviews",
    "provider.leaveReview": "Leave a Review",
    "provider.shareExperience": "Share your experience...",
    "provider.submitReview": "Submit Review",
    "provider.submitting": "Submitting...",
    "provider.noReviews": "No reviews yet. Be the first to review!",
    "provider.notFound": "Provider not found",
    "provider.backToDiscover": "Back to Discover",
    "provider.confirmAndBook": "Confirm and Book",
    "provider.selectServiceTime": "Select service & time",
    "provider.total": "Total",
    "provider.bookingConfirmed": "Booking Confirmed!",
    "provider.appointmentScheduled": "Your appointment with",
    "provider.hasBeenScheduled": "has been scheduled for",
    "provider.at": "at",
    "provider.redirecting": "Redirecting to home...",
    "provider.loading": "Loading provider...",
    "provider.verified": "Verified",
    "provider.manageWork": "Manage Work",
    "provider.noPortfolio": "No portfolio added yet.",
    "provider.reviewsHint": "No reviews yet. Reviews will appear once clients book your services.",
    "provider.reviewsInactiveHint": "No reviews yet. Reviews will appear once your profile is active.",
    "provider.activateHint": "Complete verification to activate your profile",
    "provider.verifPending": "Verification pending",
    "provider.verifiedBy": "Verified by",
    "provider.cnamCertified": "CNAM Certified Artisan",
    "provider.anaeCertified": "ANAE Auto-Entrepreneur",
    "provider.verifiedProfile": "Verified Profile",

    // Search
    "search.title": "Search",
    "search.placeholder": "Search providers...",
    "search.sortBy": "Sort by:",
    "search.rating": "Rating",
    "search.reviewsSort": "Reviews",
    "search.price": "Price",
    "search.providersFound": "providers found",
    "search.providerFound": "provider found",
    "search.loading": "Loading...",
    "search.noResults": "No results found",
    "search.noResultsHint": "Try different keywords or filters",
    "search.recent": "Recent",
    "search.popular": "Popular",
    "search.trending": "Trending",
    "search.clearAll": "Clear all",
    "search.filterByOrder": "Filter by Order / Body",
    "search.filterByTrade": "Filter by Trade",
    "search.filterByActivity": "Filter by Activity",
    "search.allSubcategories": "All",
    "search.locationPlaceholder": "Filter by Wilaya",
    "search.allWilayas": "All Wilayas",
    "search.allCategories": "All Categories",
    "search.selectCategory": "Select Category",
    "search.chooseCategoryFirst": "Choose a category first",

    // Bookings
    "bookings.title": "My Bookings",
    "bookings.upcoming": "upcoming",
    "bookings.completed": "completed",
    "bookings.cancelled": "cancelled",
    "bookings.noBookings": "No {status} bookings",
    "bookings.bookService": "Book a service to get started",
    "bookings.noAppointments": "You don't have any {status} appointments",
    "bookings.browseServices": "Browse Services",

    // Favorites
    "favorites.title": "Saved Providers",
    "favorites.noSaved": "No saved providers",
    "favorites.noSavedHint": "Save providers to quickly find them later",
    "favorites.browse": "Browse providers",

    // Settings
    "settings.title": "Settings",
    "settings.account": "Account",
    "settings.editProfile": "Edit Profile",
    "settings.notifications": "Notifications",
    "settings.privacySecurity": "Privacy & Security",
    "settings.bookings": "Bookings",
    "settings.paymentMethods": "Payment Methods",
    "settings.savedProviders": "Saved Providers",
    "settings.preferences": "Preferences",
    "settings.language": "Language",
    "settings.darkMode": "Dark Mode",
    "settings.support": "Support",
    "settings.helpCenter": "Help Center",
    "settings.termsOfService": "Terms of Service",
    "settings.logOut": "Log Out",
    "settings.business": "Business",
    "settings.manageServices": "Manage Services",

    // Dashboard & Services
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome back!",
    "dashboard.overview": "Here's your business overview",
    "services.title": "My Services",
    "services.add": "Add",
    "services.addService": "Add Service",
    "services.addNewService": "Add New Service",
    "services.editService": "Edit Service",
    "services.noServices": "No services yet",
    "services.noServicesDesc": "Add your first service to start accepting bookings",
    "services.name": "Service Name",
    "services.namePlaceholder": "e.g., Video Consultation",
    "services.description": "Description",
    "services.descriptionPlaceholder": "Brief description of the service",
    "services.price": "Price (DA)",
    "services.duration": "Duration (min)",
    "services.cancel": "Cancel",
    "services.saveChanges": "Save Changes",

    // File Upload
    "upload.invalidType": "Invalid file type. Please upload PNG or JPG only.",
    "upload.tooLarge": "File too large. Maximum size is 4MB.",
    "upload.dragDrop": "Drag and drop or click to browse",
    "upload.chooseFile": "Choose File",
    "upload.limitHint": "Must be a PNG or JPG (4MB max)",

    // Webcam
    "webcam.error": "Unable to access camera. Please check camera permissions in your browser.",
    "webcam.tryAgain": "Try Again",
    "webcam.initializing": "Initializing camera...",
    "webcam.retake": "Retake Photo",
    "webcam.capture": "Capture Selfie",

    // Theme
    "theme.system": "System",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.off": "Off",
    "theme.on": "On",

    // Language names
    "lang.en": "English",
    "lang.fr": "Français",
    "lang.ar": "العربية",

    // Common
    "common.loading": "Loading...",
    "common.error": "Something went wrong",

    // Home page
    "home.title": "Find the perfect service",
    "home.subtitle": "Browse our directory of top-rated services from trusted professionals.",
    "home.noServices": "No services found.",
    "home.logIn": "Log In",
    "home.signUp": "Sign Up",

    // Login
    "login.title": "Welcome Back",
    "login.subtitle": "Sign in to your account to continue",
    "login.iam": "I am a...",
    "login.serviceProvider": "Service Provider",
    "login.consumer": "Consumer",
    "login.emailOrPhone": "Email",
    "login.emailPlaceholder": "Enter your email",
    "login.emailRequired": "Email is required",
    "login.password": "Password",
    "login.passwordPlaceholder": "Enter your password",
    "login.passwordRequired": "Password is required",
    "login.forgotPassword": "Forgot password?",
    "login.roleRequired": "Please select your role",
    "login.signingIn": "Signing in...",
    "login.signIn": "Sign In",
    "login.noAccount": "Don't have an account?",
    "login.signUp": "Sign up",
    "login.failed": "Login failed",
    "login.unexpectedError": "An unexpected error occurred",

    // Signup
    "signup.createAccount": "Create Your Account",
    "signup.profileDetails": "Profile Details",
    "signup.initialSetup": "Initial Service Setup",
    "signup.subtitle1": "Join Qantara today to get started",
    "signup.subtitle2": "Tell clients a little bit about who you are",
    "signup.subtitle3": "Let us know what you do",
    "signup.roleSelect": "I want to sign up as a:",
    "signup.fullName": "Full Name",
    "signup.fullNamePlaceholder": "Enter your full name",
    "signup.termsAgree": "I agree to the",
    "signup.termsLink": "Terms of Service",
    "signup.and": "and",
    "signup.privacyLink": "Privacy Policy",
    "signup.roleRequired": "Please select a role",
    "signup.fullNameRequired": "Full Name is required",
    "signup.termsRequired": "You must agree to the terms and conditions",
    "signup.processing": "Processing...",
    "signup.completeSignUp": "Complete Sign Up",
    "signup.continue": "Continue",
    "signup.skip": "Skip for now",
    "signup.skipAndFinish": "Skip & Finish",
    "signup.proTitle": "Professional Title",
    "signup.proTitlePlaceholder": "e.g. Family Physician",
    "signup.phone": "Contact Phone Number",
    "signup.bio": "About (Bio)",
    "signup.bioPlaceholder": "Tell clients about your experience...",
    "signup.serviceName": "Initial Service Name",
    "signup.serviceNamePlaceholder": "e.g. Comprehensive Checkup",
    "signup.servicePrice": "Base Price (DA)",
    "signup.emailVerified": "Email Verified!",
    "signup.redirecting": "Redirecting to login...",
    "signup.enterCode": "Enter verification code",
    "signup.codeSentTo": "We sent a 6-digit code to",
    "signup.enterFullCode": "Please enter the full 6-digit code",
    "signup.verifying": "Verifying...",
    "signup.verifyEmail": "Verify Email",
    "signup.resendCode": "Resend code",
    "signup.resendCodeIn": "Resend code in",
    "signup.resendFailed": "Failed to resend code",
    "signup.subtitle": "Access top providers and discover services easily",
    "signup.username": "Username",
    "signup.usernamePlaceholder": "Enter your username",
    "signup.usernameRequired": "Username is required",
    "signup.emailOrPhone": "Email",
    "signup.emailPlaceholder": "Enter your email",
    "signup.emailRequired": "Email is required",
    "signup.emailInvalid": "Please enter a valid email address",
    "signup.password": "Password",
    "signup.passwordPlaceholder": "Create a password",
    "signup.passwordRequired": "Password is required",
    "signup.passwordTooShort": "Password must be at least 8 characters",
    "signup.confirmPassword": "Confirm Password",
    "signup.confirmPasswordPlaceholder": "Confirm your password",
    "signup.passwordsNoMatch": "Passwords do not match",
    "signup.creatingAccount": "Creating Account...",
    "signup.signUp": "Sign Up",
    "signup.haveAccount": "Already have an account?",
    "signup.signIn": "Sign in",
    "signup.failed": "Signup failed",
    "signup.unexpectedError": "An unexpected error occurred",

    // Provider details extras
    "provider.servicesOffered": "Services Offered",
    "provider.noServices": "No services listed.",
    "provider.contactDetails": "Log in to view contact details",
    "provider.selectServiceToReview": "Select a service to review...",
    "provider.noServicesToReview": "This provider currently has no services to review.",
    "provider.logInToReview": "Log in to leave a review.",

    // Modern layout redesign translations
    "nav.becomeProvider": "Become Provider",
    "nav.installApp": "Install App",
    "nav.installHintiOS": "To install, tap Share then 'Add to Home Screen'.",
    "hero.title": "Find the best professionals in Algeria",
    "hero.subtitle": "Regulated professions, artisans, auto-entrepreneurs — verified and available now.",
    "hero.searchPlaceholder": "What service are you looking for?",
    "hero.popular": "Popular:",
    "trust.verified": "500+ verified professionals",
    "trust.satisfied": "10,000+ satisfied clients",
    "trust.aiVerification": "AI verification of certificates",
    "trust.authentic": "100% authentic profiles",
    "provider.from": "From",
    "provider.contact": "Contact",
    "provider.getQuote": "Get a Quote",
    "provider.responseTime": "Responds in less than 2h",
    "provider.memberSince": "Member since",
    "provider.languages": "Languages",
    "provider.location": "Location",
    "footer.categories": "Categories",
    "footer.about": "About",
    "footer.support": "Support",
    "footer.legal": "Legal",
    "footer.social": "Social",
    "footer.rightsReserved": "All rights reserved.",

    // Consumer Profile & Notifications
    "notifications.title": "Notifications",
    "notifications.emptyTitle": "You're all caught up!",
    "notifications.emptyDesc": "No new notifications. We'll let you know when something comes up.",
    "notifications.browse": "Browse Providers",
    "profile.title": "Profile",
    "profile.guest": "Guest User",
    "profile.signInHint": "Sign in to access your profile",
    "profile.edit": "Edit",
    "profile.menu.favorites": "Favorites",
    "profile.menu.favoritesDesc": "Providers you have saved",
    "profile.menu.payments": "Payment Methods",
    "profile.menu.paymentsDesc": "Manage your payment options",
    "profile.menu.notifications": "Notification Settings",
    "profile.menu.notificationsDesc": "Customize your alerts",
    "profile.menu.support": "Help & Support",
    "profile.menu.supportDesc": "FAQs and contact support",
    "profile.signOut": "Sign Out",

    // Provider Verification & Profile completion
    "verify.banner.pending.title": "Verification Pending Review",
    "verify.banner.pending.msg": "We have successfully received your documents! Gemini AI has pre-audited your face and name matches. An administrator will perform the final manual review shortly.",
    "verify.banner.rejected.title": "Verification Rejected",
    "verify.banner.rejected.msg": "Your verification documents were rejected. Please re-submit.",
    "verify.banner.pendingVerif.title": "Account Pending Verification",
    "verify.banner.pendingVerif.msg": "Complete verification by uploading your Government ID, a live camera selfie, and your professional certificate to activate your profile.",
    "verify.resubmitBtn": "Re-submit Verification Documents",
    "verify.startBtn": "Start Verification Workflow",
    "verify.identity.title": "Identity Verification",
    "verify.identity.desc": "Verify your identity using Didit IDV or by uploading your ID card and taking a selfie manually.",
    "verify.identity.status": "Identity Status",
    "verify.professional.title": "Professional Credentials",
    "verify.professional.desc": "Upload your professional card (carte d'artisan, carte d'auto-entrepreneur, etc.) so we can verify your credentials.",
    "verify.professional.status": "Professional Status",
    "verify.activity.other": "Other (Custom activity)",
    "verify.activity.customLabel": "Custom Activity Name",
    "verify.activity.customPlaceholder": "Enter your professional activity",
    "verify.identity.startBtn": "Verify Identity",
    "verify.professional.startBtn": "Verify Credentials",
    "verify.manual.title": "Verify Manually",
    "verify.manual.idLabel": "Upload ID Card / Passport",
    "verify.manual.selfieLabel": "Upload Selfie Image",
    "verify.dialog.title": "Identity & Credential Verification",
    "verify.dialog.step": "Step {step} of 3: {name}",
    "verify.step.category": "Professional Category",
    "verify.step.yoti": "ID & Liveness (Didit)",
    "verify.step.credentials": "Professional Credentials",
    "verify.step2.prompt.yoti": "Complete the identity verification check and liveness selfie capture below using Didit IDV.",
    "verify.category.prompt": "Select your professional category and enter your official registration details.",
    "verify.cat.regulated.desc": "Doctors, pharmacists, lawyers, notaries... Verification via your professional Order.",
    "verify.cat.artisan.desc": "Electricians, plumbers, carpenters, hairdressers... Verification via CNAM Artisan Card.",
    "verify.cat.auto.desc": "Developers, designers, marketers... Verification via ANAE Auto-Entrepreneur Card.",
    "verify.regulatory.label": "Your Order / Professional Body",
    "verify.regulatory.placeholder": "Select your Order",
    "verify.regulatory.group": "Councils of the Order",
    "verify.license.label": "Registration number in the Order registry",
    "verify.license.placeholder": "e.g. 12345/2020 or DOC-12345",
    "verify.trade.label": "Your trade",
    "verify.trade.placeholder": "Select your trade",
    "verify.cnam.label": "CNAM Artisan Card Number",
    "verify.cnam.placeholder": "e.g. 16-123456-20",
    "verify.activity.label": "Your main activity",
    "verify.activity.placeholder": "Select your activity",
    "verify.anae.label": "ANAE Auto-Entrepreneur Card Number",
    "verify.anae.placeholder": "e.g. AE-123456-2024",
    "verify.secondary.label": "Secondary activities (optional)",
    "verify.secondary.placeholder": "e.g. Consulting, Training...",
    "verify.secondary.addBtn": "Add secondary activity",
    "verify.next.id": "Next: Upload Government ID",
    "verify.step2.prompt": "Please upload a clear scan or photo of your official government ID card, passport, or driver's license.",
    "verify.step2.uploadLabel": "Upload ID Card or Passport",
    "verify.back": "Back",
    "verify.next.selfie": "Next: Take Live Selfie",
    "verify.step3.prompt": "Position your face inside the camera area and take a photo. This ensures the selfie is captured live by the camera and helps verify you own the uploaded ID.",
    "verify.next.docs": "Next: Upload Category Card / Cert",
    "verify.step4.prompt": "Upload a scan of your official professional card or certificate document corresponding to your category.",
    "verify.step4.uploadReg": "Upload Certificate of the Order",
    "verify.step4.uploadArt": "Upload Carte d'Artisan CNAM (recto-verso)",
    "verify.step4.uploadAuto": "Upload Carte d'Auto-Entrepreneur ANAE (recto-verso)",
    "verify.audit.running": "Gemini is running automated face & name matching audits...",
    "verify.submitBtn": "Submit to Admin Panel",
    "verify.audit.analyzing": "Analyzing Audit...",
    "verify.audit.success": "Submission Received!",
    "verify.audit.desc": "Gemini has successfully completed the automated pre-verification checks. Here are the findings saved to the admin review logs:",
    "verify.audit.faceOk": "Face Check: Faces match official ID card",
    "verify.audit.faceFail": "Face Check: AI flagged potential face mismatch",
    "verify.audit.nameOk": "Name Check: Holder name matches ID card",
    "verify.audit.nameFail": "Name Check: AI flagged potential name discrepancy",
    "verify.audit.adminHint": "An administrator will verify these results and activate your account profile within 1-2 business days.",
    "wizard.step": "Step {step} of 3: {name}",
    "wizard.step.basic": "Basic Info",
    "wizard.step.services": "Services Setup",
    "wizard.step.portfolio": "Portfolio",
    "wizard.photo": "Profile Photo",
    "wizard.location": "Location (Wilaya)",
    "wizard.locationPlaceholder": "Select your Wilaya",
    "wizard.category": "Category",
    "wizard.categoryHint": "Your professional category is defined by your verification documents and cannot be modified.",
    "wizard.bio": "Your Bio / About Me",
    "wizard.bioPlaceholder": "Tell clients about your experience and expertise...",
    "wizard.saveNext": "Save & Next: Services",
    "wizard.step2.desc": "Add the services you offer, including the price and expected duration.",
    "wizard.service.placeholder": "Service Name (e.g. Plumbing Repair)",
    "wizard.price.placeholder": "Price",
    "wizard.duration.placeholder": "Duration",
    "wizard.addService": "+ Add Service",
    "wizard.back": "Back",
    "wizard.saveNextPortfolio": "Save & Next: Portfolio",
    "wizard.step3.desc": "Upload images of your past work to show clients what you can do. Add image URLs below: (e.g. https://imgur.com/your-image.jpg)",
    "wizard.imgUrl.placeholder": "Image URL",
    "wizard.emptyPortfolio": "No portfolio images added yet. You can skip this step and add them later.",
    "wizard.addPortfolioImg": "+ Add Portfolio Image",
    "wizard.readyTitle": "Ready to go live!",
    "wizard.readyDesc": "By activating, your profile will be publicly visible to all clients seeking your services.",
    "wizard.saving": "Saving...",
    "wizard.goPublic": "Go Public",
  },
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.search": "Recherche",
    "nav.notifications": "Notifications",
    "nav.profile": "Profil",

    // Discover
    "discover.browseCategories": "Parcourir les catégories",
    "discover.all": "Tout",
    "discover.featuredProviders": "Prestataires en vedette",
    "discover.topRated": "Les mieux notés",
    "discover.viewAll": "Voir tout",
    "discover.seeMore": "Voir plus",
    "discover.noProviders": "Aucun prestataire trouvé",
    "discover.noProvidersHint": "Essayez d'ajuster votre recherche ou vos filtres",
    "discover.searchPlaceholder": "Rechercher médecins, artisans, auto-entrepreneurs...",
    "discover.reviews": "avis",

    // Categories
    "regulated_profession": "Professions Libérales Réglementées",
    "artisan": "Artisans & Métiers Techniques",
    "auto_entrepreneur": "Auto-Entrepreneurs",

    // App name
    "app.name": "Qantara",

    // Provider Details
    "provider.about": "À propos",
    "provider.selectService": "Choisir un service",
    "provider.selectDateTime": "Choisir la date et l'heure",
    "provider.availableTimes": "Horaires disponibles pour le",
    "provider.reviews": "Avis",
    "provider.leaveReview": "Laisser un avis",
    "provider.shareExperience": "Partagez votre expérience...",
    "provider.submitReview": "Envoyer l'avis",
    "provider.submitting": "Envoi en cours...",
    "provider.noReviews": "Aucun avis. Soyez le premier à donner votre avis !",
    "provider.notFound": "Prestataire introuvable",
    "provider.backToDiscover": "Retour à la découverte",
    "provider.confirmAndBook": "Confirmer et réserver",
    "provider.selectServiceTime": "Sélect. service & heure",
    "provider.total": "Total",
    "provider.bookingConfirmed": "Réservation confirmée !",
    "provider.appointmentScheduled": "Votre rendez-vous avec",
    "provider.hasBeenScheduled": "a été programmé pour le",
    "provider.at": "à",
    "provider.redirecting": "Redirection vers l'accueil...",
    "provider.loading": "Chargement du prestataire...",
    "provider.verified": "Vérifié",
    "provider.manageWork": "Gérer les travaux",
    "provider.noPortfolio": "Aucun portfolio ajouté pour l'instant.",
    "provider.reviewsHint": "Pas encore d'avis. Les avis apparaîtront lorsque les clients réserveront vos services.",
    "provider.reviewsInactiveHint": "Pas encore d'avis. Les avis apparaîtront une fois votre profil actif.",
    "provider.activateHint": "Complétez la vérification pour activer votre profil",
    "provider.verifPending": "Vérification en cours",
    "provider.verifiedBy": "Vérifié par",
    "provider.cnamCertified": "Artisan certifié CNAM",
    "provider.anaeCertified": "Auto-Entrepreneur ANAE",
    "provider.verifiedProfile": "Profil vérifié",

    // Search
    "search.title": "Recherche",
    "search.placeholder": "Rechercher des prestataires...",
    "search.sortBy": "Trier par :",
    "search.rating": "Note",
    "search.reviewsSort": "Avis",
    "search.price": "Prix",
    "search.providersFound": "prestataires trouvés",
    "search.providerFound": "prestataire trouvé",
    "search.loading": "Chargement...",
    "search.noResults": "Aucun résultat",
    "search.noResultsHint": "Essayez d'autres mots-clés ou filtres",
    "search.recent": "Récent",
    "search.popular": "Populaire",
    "search.trending": "Tendance",
    "search.clearAll": "Tout effacer",
    "search.filterByOrder": "Filtrer par Ordre / Organisme",
    "search.filterByTrade": "Filtrer par Métier",
    "search.filterByActivity": "Filtrer par Activité",
    "search.allSubcategories": "Tous",
    "search.locationPlaceholder": "Filtrer par Wilaya",
    "search.allWilayas": "Toutes les Wilayas",
    "search.allCategories": "Toutes les Catégories",
    "search.selectCategory": "Sélectionner la Catégorie",
    "search.chooseCategoryFirst": "Choisissez d'abord une catégorie",

    // Bookings
    "bookings.title": "Mes réservations",
    "bookings.upcoming": "à venir",
    "bookings.completed": "terminées",
    "bookings.cancelled": "annulées",
    "bookings.noBookings": "Aucune réservation {status}",
    "bookings.bookService": "Réservez un service pour commencer",
    "bookings.noAppointments": "Vous n'avez aucun rendez-vous {status}",
    "bookings.browseServices": "Parcourir les services",

    // Favorites
    "favorites.title": "Prestataires sauvegardés",
    "favorites.noSaved": "Aucun prestataire sauvegardé",
    "favorites.noSavedHint": "Sauvegardez des prestataires pour les retrouver facilement",
    "favorites.browse": "Parcourir les prestataires",

    // Settings
    "settings.title": "Paramètres",
    "settings.account": "Compte",
    "settings.editProfile": "Modifier le profil",
    "settings.notifications": "Notifications",
    "settings.privacySecurity": "Confidentialité et sécurité",
    "settings.bookings": "Réservations",
    "settings.paymentMethods": "Moyens de paiement",
    "settings.savedProviders": "Prestataires sauvegardés",
    "settings.preferences": "Préférences",
    "settings.language": "Langue",
    "settings.darkMode": "Mode sombre",
    "settings.support": "Assistance",
    "settings.helpCenter": "Centre d'aide",
    "settings.termsOfService": "Conditions d'utilisation",
    "settings.logOut": "Déconnexion",
    "settings.business": "Entreprise",
    "settings.manageServices": "Gérer les services",

    // Dashboard & Services
    "dashboard.title": "Tableau de bord",
    "dashboard.welcome": "Bon retour !",
    "dashboard.overview": "Voici l'aperçu de votre activité",
    "services.title": "Mes Services",
    "services.add": "Ajouter",
    "services.addService": "Ajouter un service",
    "services.addNewService": "Ajouter un nouveau service",
    "services.editService": "Modifier le service",
    "services.noServices": "Aucun service pour le moment",
    "services.noServicesDesc": "Ajoutez votre premier service pour commencer à recevoir des réservations",
    "services.name": "Nom du service",
    "services.namePlaceholder": "ex : Consultation vidéo",
    "services.description": "Description",
    "services.descriptionPlaceholder": "Brève description du service",
    "services.price": "Prix (DA)",
    "services.duration": "Durée (min)",
    "services.cancel": "Annuler",
    "services.saveChanges": "Enregistrer les modifications",

    // File Upload
    "upload.invalidType": "Type de fichier invalide. Veuillez télécharger uniquement des fichiers PNG ou JPG.",
    "upload.tooLarge": "Fichier trop volumineux. La taille maximale est de 4 Mo.",
    "upload.dragDrop": "Glissez-déposez ou cliquez pour parcourir",
    "upload.chooseFile": "Choisir le fichier",
    "upload.limitHint": "Doit être un PNG ou un JPG (4 Mo max)",

    // Webcam
    "webcam.error": "Impossible d'accéder à la caméra. Veuillez vérifier les autorisations de votre navigateur.",
    "webcam.tryAgain": "Réessayer",
    "webcam.initializing": "Initialisation de la caméra...",
    "webcam.retake": "Reprendre la photo",
    "webcam.capture": "Prendre le selfie",

    // Theme
    "theme.system": "Système",
    "theme.light": "Clair",
    "theme.dark": "Sombre",
    "theme.off": "Désactivé",
    "theme.on": "Activé",

    // Language names
    "lang.en": "English",
    "lang.fr": "Français",
    "lang.ar": "العربية",

    // Common
    "common.loading": "Chargement...",
    "common.error": "Quelque chose s'est mal passé",

    // Home
    "home.title": "Trouvez le service parfait",
    "home.subtitle": "Parcourez notre annuaire de services proposés par des professionnels de confiance.",
    "home.noServices": "Aucun service trouvé.",
    "home.logIn": "Connexion",
    "home.signUp": "S'inscrire",

    // Login
    "login.title": "Bon retour !",
    "login.subtitle": "Connectez-vous à votre compte pour continuer",
    "login.iam": "Je suis...",
    "login.serviceProvider": "Prestataire",
    "login.consumer": "Consommateur",
    "login.emailOrPhone": "E-mail",
    "login.emailPlaceholder": "Entrez votre e-mail",
    "login.emailRequired": "L'e-mail est requis",
    "login.password": "Mot de passe",
    "login.passwordPlaceholder": "Entrez votre mot de passe",
    "login.passwordRequired": "Le mot de passe est requis",
    "login.forgotPassword": "Mot de passe oublié ?",
    "login.roleRequired": "Veuillez sélectionner votre rôle",
    "login.signingIn": "Connexion en cours...",
    "login.signIn": "Se connecter",
    "login.noAccount": "Pas encore de compte ?",
    "login.signUp": "S'inscrire",
    "login.failed": "Échec de la connexion",
    "login.unexpectedError": "Une erreur inattendue s'est produite",

    // Signup
    "signup.createAccount": "Créer votre compte",
    "signup.profileDetails": "Détails du profil",
    "signup.initialSetup": "Configuration initiale du service",
    "signup.subtitle1": "Rejoignez Qantara dès aujourd'hui",
    "signup.subtitle2": "Parlez un peu de vous aux clients",
    "signup.subtitle3": "Faites-nous savoir ce que vous faites",
    "signup.roleSelect": "Je veux m'inscrire en tant que :",
    "signup.fullName": "Nom complet",
    "signup.fullNamePlaceholder": "Entrez votre nom complet",
    "signup.termsAgree": "J'accepte les",
    "signup.termsLink": "Conditions d'utilisation",
    "signup.and": "et la",
    "signup.privacyLink": "Politique de confidentialité",
    "signup.roleRequired": "Veuillez sélectionner un rôle",
    "signup.fullNameRequired": "Le nom complet est requis",
    "signup.termsRequired": "Vous devez accepter les conditions générales",
    "signup.processing": "Traitement...",
    "signup.completeSignUp": "Terminer l'inscription",
    "signup.continue": "Continuer",
    "signup.skip": "Passer pour l'instant",
    "signup.skipAndFinish": "Passer & Terminer",
    "signup.proTitle": "Titre professionnel",
    "signup.proTitlePlaceholder": "ex: Médecin de famille",
    "signup.phone": "Numéro de téléphone de contact",
    "signup.bio": "À propos (Bio)",
    "signup.bioPlaceholder": "Parlez de votre expérience aux clients...",
    "signup.serviceName": "Nom initial du service",
    "signup.serviceNamePlaceholder": "ex: Consultation générale",
    "signup.servicePrice": "Prix de base (DA)",
    "signup.emailVerified": "E-mail vérifié !",
    "signup.redirecting": "Redirection vers la page de connexion...",
    "signup.enterCode": "Entrez le code de vérification",
    "signup.codeSentTo": "Nous avons envoyé un code à 6 chiffres à",
    "signup.enterFullCode": "Veuillez entrer le code complet à 6 chiffres",
    "signup.verifying": "Vérification...",
    "signup.verifyEmail": "Vérifier l'e-mail",
    "signup.resendCode": "Renvoyer le code",
    "signup.resendCodeIn": "Renvoyer le code dans",
    "signup.resendFailed": "Échec du renvoi du code",
    "signup.subtitle": "Accédez aux meilleurs prestataires et découvrez des services facilement",
    "signup.username": "Nom d'utilisateur",
    "signup.usernamePlaceholder": "Entrez votre nom d'utilisateur",
    "signup.usernameRequired": "Le nom d'utilisateur est requis",
    "signup.emailOrPhone": "E-mail",
    "signup.emailPlaceholder": "Entrez votre e-mail",
    "signup.emailRequired": "L'e-mail est requis",
    "signup.emailInvalid": "Veuillez entrer une adresse e-mail valide",
    "signup.password": "Mot de passe",
    "signup.passwordPlaceholder": "Créez un mot de passe",
    "signup.passwordRequired": "Le mot de passe est requis",
    "signup.passwordTooShort": "Le mot de passe doit contenir au moins 8 caractères",
    "signup.confirmPassword": "Confirmer le mot de passe",
    "signup.confirmPasswordPlaceholder": "Confirmez votre mot de passe",
    "signup.passwordsNoMatch": "Les mots de passe ne correspondent pas",
    "signup.creatingAccount": "Création du compte...",
    "signup.signUp": "S'inscrire",
    "signup.haveAccount": "Déjà un compte ?",
    "signup.signIn": "Se connecter",
    "signup.failed": "Échec de l'inscription",
    "signup.unexpectedError": "Une erreur inattendue s'est produite",

    // Provider details extras
    "provider.servicesOffered": "Services proposés",
    "provider.noServices": "Aucun service répertorié.",
    "provider.contactDetails": "Connectez-vous pour voir les coordonnées",
    "provider.selectServiceToReview": "Sélectionnez un service à évaluer...",
    "provider.noServicesToReview": "Ce prestataire n'a actuellement aucun service à évaluer.",
    "provider.logInToReview": "Connectez-vous pour laisser un avis.",

    // Modern layout redesign translations
    "nav.becomeProvider": "Devenir Prestataire",
    "nav.installApp": "Installer l'App",
    "nav.installHintiOS": "Pour installer, appuyez sur Partager puis 'Sur l'écran d'accueil'.",
    "hero.title": "Trouvez les meilleurs professionnels en Algérie",
    "hero.subtitle": "Professions réglementées, artisans, auto-entrepreneurs — vérifiés et disponibles maintenant.",
    "hero.searchPlaceholder": "Quel service recherchez-vous ?",
    "hero.popular": "Populaire :",
    "trust.verified": "500+ professionnels vérifiés",
    "trust.satisfied": "10 000+ clients satisfaits",
    "trust.aiVerification": "Vérification IA des certificats",
    "trust.authentic": "Profils 100% authentiques",
    "provider.from": "À partir de",
    "provider.contact": "Contacter",
    "provider.getQuote": "Obtenir un devis",
    "provider.responseTime": "Répond en moins de 2h",
    "provider.memberSince": "Membre depuis",
    "provider.languages": "Langues",
    "provider.location": "Localisation",
    "footer.categories": "Catégories",
    "footer.about": "À propos",
    "footer.support": "Assistance",
    "footer.legal": "Légal",
    "footer.social": "Réseaux sociaux",
    "footer.rightsReserved": "Tous droits réservés.",

    // Consumer Profile & Notifications
    "notifications.title": "Notifications",
    "notifications.emptyTitle": "Vous êtes à jour !",
    "notifications.emptyDesc": "Aucune nouvelle notification. Nous vous préviendrons dès qu'il y aura du nouveau.",
    "notifications.browse": "Parcourir les prestataires",
    "profile.title": "Profil",
    "profile.guest": "Utilisateur invité",
    "profile.signInHint": "Connectez-vous pour accéder à votre profil",
    "profile.edit": "Modifier",
    "profile.menu.favorites": "Favoris",
    "profile.menu.favoritesDesc": "Prestataires que vous avez sauvegardés",
    "profile.menu.payments": "Moyens de paiement",
    "profile.menu.paymentsDesc": "Gérer vos options de paiement",
    "profile.menu.notifications": "Paramètres de notification",
    "profile.menu.notificationsDesc": "Personnaliser vos alertes",
    "profile.menu.support": "Aide & Assistance",
    "profile.menu.supportDesc": "FAQ et contacter le support",
    "profile.signOut": "Déconnexion",

    // Provider Verification & Profile completion
    "verify.banner.pending.title": "Vérification en attente de révision",
    "verify.banner.pending.msg": "Nous avons bien reçu vos documents ! L'IA Gemini a pré-vérifié la correspondance de votre visage et de votre nom. Un administrateur effectuera la révision manuelle finale sous peu.",
    "verify.banner.rejected.title": "Vérification rejetée",
    "verify.banner.rejected.msg": "Vos documents de vérification ont été rejetés. Veuillez les soumettre à nouveau.",
    "verify.banner.pendingVerif.title": "Compte en attente de vérification",
    "verify.banner.pendingVerif.msg": "Complétez la vérification en téléchargeant votre pièce d'identité officielle, un selfie en direct et votre certificat professionnel pour activer votre profil.",
    "verify.resubmitBtn": "Soumettre à nouveau les documents de vérification",
    "verify.startBtn": "Démarrer le processus de vérification",
    "verify.identity.title": "Vérification d'Identité",
    "verify.identity.desc": "Vérifiez votre identité via Didit IDV ou en téléchargeant manuellement votre pièce d'identité et un selfie.",
    "verify.identity.status": "Statut d'Identité",
    "verify.professional.title": "Identifiants Professionnels",
    "verify.professional.desc": "Téléchargez votre carte professionnelle (carte d'artisan, carte d'auto-entrepreneur, etc.) pour vérifier vos compétences.",
    "verify.professional.status": "Statut Professionnel",
    "verify.activity.other": "Autre (Activité personnalisée)",
    "verify.activity.customLabel": "Nom de l'activité personnalisée",
    "verify.activity.customPlaceholder": "Entrez votre activité professionnelle",
    "verify.identity.startBtn": "Vérifier l'Identité",
    "verify.professional.startBtn": "Vérifier les Identifiants",
    "verify.manual.title": "Vérifier Manuellement",
    "verify.manual.idLabel": "Télécharger la Pièce d'Identité / Passeport",
    "verify.manual.selfieLabel": "Télécharger l'Image de Selfie",
    "verify.dialog.title": "Vérification d'identité et de diplôme",
    "verify.dialog.step": "Étape {step} sur 3 : {name}",
    "verify.step.category": "Catégorie professionnelle",
    "verify.step.yoti": "ID & Selfie (Didit)",
    "verify.step.credentials": "Justificatifs professionnels",
    "verify.step2.prompt.yoti": "Veuillez effectuer la vérification d'identité et la capture de selfie ci-dessous via Didit IDV.",
    "verify.category.prompt": "Sélectionnez votre catégorie professionnelle et saisissez vos informations officielles d'inscription.",
    "verify.cat.regulated.desc": "Médecins, pharmaciens, avocats, notaires... Vérification par votre Ordre professionnel.",
    "verify.cat.artisan.desc": "Électriciens, plombiers, menuisiers, coiffeurs... Vérification par Carte d'Artisan CNAM.",
    "verify.cat.auto.desc": "Développeurs, designers, marketers... Vérification par Carte d'Auto-Entrepreneur ANAE.",
    "verify.regulatory.label": "Votre Ordre / Instance professionnelle",
    "verify.regulatory.placeholder": "Sélectionnez votre Ordre",
    "verify.regulatory.group": "Conseils de l'Ordre",
    "verify.license.label": "Numéro d'inscription au tableau de l'Ordre",
    "verify.license.placeholder": "Ex : 12345/2020 ou DOC-12345",
    "verify.trade.label": "Votre métier",
    "verify.trade.placeholder": "Sélectionnez votre métier",
    "verify.cnam.label": "Numéro de Carte d'Artisan CNAM",
    "verify.cnam.placeholder": "Ex : 16-123456-20",
    "verify.activity.label": "Votre activité principale",
    "verify.activity.placeholder": "Sélectionnez votre activité",
    "verify.anae.label": "Numéro de Carte d'Auto-Entrepreneur ANAE",
    "verify.anae.placeholder": "Ex : AE-123456-2024",
    "verify.secondary.label": "Activités secondaires (optionnel)",
    "verify.secondary.placeholder": "Ex : Consulting, Formation...",
    "verify.secondary.addBtn": "Ajouter une activité secondaire",
    "verify.next.id": "Suivant : Télécharger la pièce d'identité",
    "verify.step2.prompt": "Veuillez télécharger un scan ou une photo claire de votre carte d'identité officielle, passeport ou permis de conduire.",
    "verify.step2.uploadLabel": "Télécharger la pièce d'identité ou le passeport",
    "verify.back": "Retour",
    "verify.next.selfie": "Suivant : Prendre un selfie en direct",
    "verify.step3.prompt": "Positionnez votre visage dans la zone de la caméra et prenez une photo. Cela garantit que le selfie est capturé en direct et permet de vérifier que vous êtes bien le propriétaire de la pièce d'identité.",
    "verify.next.docs": "Suivant : Télécharger la carte / certif. de catégorie",
    "verify.step4.prompt": "Téléchargez un scan de votre carte professionnelle officielle ou de votre certificat correspondant à votre catégorie.",
    "verify.step4.uploadReg": "Télécharger le certificat de l'Ordre",
    "verify.step4.uploadArt": "Télécharger la Carte d'Artisan CNAM (recto-verso)",
    "verify.step4.uploadAuto": "Télécharger la Carte d'Auto-Entrepreneur ANAE (recto-verso)",
    "verify.audit.running": "Gemini effectue des audits automatisés de correspondance des visages et des noms...",
    "verify.submitBtn": "Soumettre au panneau d'administration",
    "verify.audit.analyzing": "Analyse de l'audit...",
    "verify.audit.success": "Soumission reçue !",
    "verify.audit.desc": "Gemini a terminé avec succès les vérifications automatisées préalables. Voici les résultats enregistrés dans les rapports d'administration :",
    "verify.audit.faceOk": "Vérification faciale : Les visages correspondent à la pièce d'identité officielle",
    "verify.audit.faceFail": "Vérification faciale : L'IA a signalé une non-correspondance potentielle",
    "verify.audit.nameOk": "Vérification du nom : Le nom correspond à la pièce d'identité",
    "verify.audit.nameFail": "Vérification du nom : L'IA a signalé une divergence potentielle",
    "verify.audit.adminHint": "Un administrateur vérifiera ces résultats et activera votre profil sous 1 à 2 jours ouvrables.",
    "wizard.step": "Étape {step} sur 3 : {name}",
    "wizard.step.basic": "Informations de base",
    "wizard.step.services": "Configuration des services",
    "wizard.step.portfolio": "Portfolio",
    "wizard.photo": "Photo de profil",
    "wizard.location": "Localisation (Wilaya)",
    "wizard.locationPlaceholder": "Sélectionnez votre Wilaya",
    "wizard.category": "Catégorie",
    "wizard.categoryHint": "Votre catégorie professionnelle est définie par vos documents de vérification et ne peut être modifiée.",
    "wizard.bio": "Votre Bio / À propos de moi",
    "wizard.bioPlaceholder": "Parlez aux clients de votre expérience et de votre expertise...",
    "wizard.saveNext": "Enregistrer & Suivant : Services",
    "wizard.step2.desc": "Ajoutez les services que vous proposez, y compris le prix et la durée prévue.",
    "wizard.service.placeholder": "Nom du service (ex: Réparation plomberie)",
    "wizard.price.placeholder": "Prix",
    "wizard.duration.placeholder": "Durée",
    "wizard.addService": "+ Ajouter un service",
    "wizard.back": "Retour",
    "wizard.saveNextPortfolio": "Enregistrer & Suivant : Portfolio",
    "wizard.step3.desc": "Téléchargez des images de vos travaux passés pour montrer aux clients ce que vous savez faire. Ajoutez des URL d'images ci-dessous : (ex : https://imgur.com/votre-image.jpg)",
    "wizard.imgUrl.placeholder": "URL de l'image",
    "wizard.emptyPortfolio": "Aucune image de portfolio ajoutée pour l'instant. Vous pouvez passer cette étape et les ajouter plus tard.",
    "wizard.addPortfolioImg": "+ Ajouter une image de portfolio",
    "wizard.readyTitle": "Prêt à être publié !",
    "wizard.readyDesc": "En activant, votre profil sera visible publiquement par tous les clients recherchant vos services.",
    "wizard.saving": "Enregistrement...",
    "wizard.goPublic": "Publier le profil",
  },
  ar: {
    // Navigation
    "nav.home": "الرئيسية",
    "nav.search": "بحث",
    "nav.notifications": "الإشعارات",
    "nav.profile": "الملف الشخصي",

    // Discover
    "discover.browseCategories": "تصفح الفئات",
    "discover.all": "الكل",
    "discover.featuredProviders": "مقدمو خدمات مميزون",
    "discover.topRated": "الأعلى تقييماً",
    "discover.viewAll": "عرض الكل",
    "discover.seeMore": "عرض المزيد",
    "discover.noProviders": "لم يتم العثور على مقدمي خدمات",
    "discover.noProvidersHint": "حاول تعديل البحث أو الفلاتر",
    "discover.searchPlaceholder": "ابحث عن أطباء، حرفيين، مقاولين ذاتيين...",
    "discover.reviews": "تقييمات",

    // Categories
    "regulated_profession": "المهن الحرة المنظمة",
    "artisan": "الحرفيين والمهن التقنية",
    "auto_entrepreneur": "مقاولون ذاتيون",

    // App name
    "app.name": "قنطرة",

    // Provider Details
    "provider.about": "نبذة",
    "provider.selectService": "اختر خدمة",
    "provider.selectDateTime": "اختر التاريخ والوقت",
    "provider.availableTimes": "الأوقات المتاحة لـ",
    "provider.reviews": "التقييمات",
    "provider.leaveReview": "اترك تقييماً",
    "provider.shareExperience": "شارك تجربتك...",
    "provider.submitReview": "إرسال التقييم",
    "provider.submitting": "جاري الإرسال...",
    "provider.noReviews": "لا توجد تقييمات بعد. كن أول من يقيّم!",
    "provider.notFound": "مقدم الخدمة غير موجود",
    "provider.backToDiscover": "العودة للاستكشاف",
    "provider.confirmAndBook": "تأكيد والحجز",
    "provider.selectServiceTime": "اختر الخدمة والوقت",
    "provider.total": "المجموع",
    "provider.bookingConfirmed": "تم تأكيد الحجز!",
    "provider.appointmentScheduled": "موعدك مع",
    "provider.hasBeenScheduled": "تم جدولته في",
    "provider.at": "الساعة",
    "provider.redirecting": "جاري التحويل للرئيسية...",
    "provider.loading": "جاري تحميل بيانات مقدم الخدمة...",
    "provider.verified": "موثّق",
    "provider.manageWork": "إدارة الأعمال",
    "provider.noPortfolio": "لم يتم إضافة معرض أعمال بعد.",
    "provider.reviewsHint": "لا توجد تقييمات بعد. ستظهر التقييمات بمجرد حجز العملاء لخدماتك.",
    "provider.reviewsInactiveHint": "لا توجد تقييمات بعد. ستظهر التقييمات بمجرد تفعيل ملفك الشخصي.",
    "provider.activateHint": "أكمل التحقق لتفعيل ملفك الشخصي",
    "provider.verifPending": "قيد التحقق",
    "provider.verifiedBy": "موثق من طرف",
    "provider.cnamCertified": "حرفي معتمد من CNAM",
    "provider.anaeCertified": "مقاول ذاتي ANAE",
    "provider.verifiedProfile": "ملف شخصي موثق",

    // Search
    "search.title": "بحث",
    "search.placeholder": "ابحث عن مقدمي خدمات...",
    "search.sortBy": "ترتيب حسب:",
    "search.rating": "التقييم",
    "search.reviewsSort": "المراجعات",
    "search.price": "السعر",
    "search.providersFound": "مقدمي خدمات",
    "search.providerFound": "مقدم خدمة",
    "search.loading": "جاري التحميل...",
    "search.noResults": "لا توجد نتائج",
    "search.noResultsHint": "جرّب كلمات مختلفة أو فلاتر أخرى",
    "search.recent": "الأخيرة",
    "search.popular": "شائعة",
    "search.trending": "الأكثر رواجاً",
    "search.clearAll": "مسح الكل",
    "search.filterByOrder": "تصفية حسب الهيئة / المنظمة",
    "search.filterByTrade": "تصفية حسب الحرفة / المهنة",
    "search.filterByActivity": "تصفية حسب النشاط",
    "search.allSubcategories": "الكل",
    "search.locationPlaceholder": "تصفية حسب الولاية",
    "search.allWilayas": "كل الولايات",
    "search.allCategories": "جميع الفئات",
    "search.selectCategory": "اختر الفئة",
    "search.chooseCategoryFirst": "اختر فئة أولاً",

    // Bookings
    "bookings.title": "حجوزاتي",
    "bookings.upcoming": "القادمة",
    "bookings.completed": "المكتملة",
    "bookings.cancelled": "الملغاة",
    "bookings.noBookings": "لا توجد حجوزات {status}",
    "bookings.bookService": "احجز خدمة للبدء",
    "bookings.noAppointments": "ليس لديك مواعيد {status}",
    "bookings.browseServices": "تصفح الخدمات",

    // Favorites
    "favorites.title": "مقدمو الخدمات المحفوظون",
    "favorites.noSaved": "لا يوجد مقدمو خدمات محفوظون",
    "favorites.noSavedHint": "احفظ مقدمي الخدمات للعثور عليهم بسرعة لاحقاً",
    "favorites.browse": "تصفح مقدمي الخدمات",

    // Settings
    "settings.title": "الإعدادات",
    "settings.account": "الحساب",
    "settings.editProfile": "تعديل الملف الشخصي",
    "settings.notifications": "الإشعارات",
    "settings.privacySecurity": "الخصوصية والأمان",
    "settings.bookings": "الحجوزات",
    "settings.paymentMethods": "وسائل الدفع",
    "settings.savedProviders": "مقدمو الخدمات المحفوظون",
    "settings.preferences": "التفضيلات",
    "settings.language": "اللغة",
    "settings.darkMode": "الوضع الداكن",
    "settings.support": "الدعم",
    "settings.helpCenter": "مركز المساعدة",
    "settings.termsOfService": "شروط الخدمة",
    "settings.logOut": "تسجيل الخروج",
    "settings.business": "الأعمال",
    "settings.manageServices": "إدارة الخدمات",

    // Dashboard & Services
    "dashboard.title": "لوحة التحكم",
    "dashboard.welcome": "مرحباً بعودتك!",
    "dashboard.overview": "إليك نظرة عامة على عملك",
    "services.title": "خدماتي",
    "services.add": "إضافة",
    "services.addService": "إضافة خدمة",
    "services.addNewService": "إضافة خدمة جديدة",
    "services.editService": "تعديل الخدمة",
    "services.noServices": "لا توجد خدمات بعد",
    "services.noServicesDesc": "أضف خدمتك الأولى لبدء قبول الحجوزات",
    "services.name": "اسم الخدمة",
    "services.namePlaceholder": "مثال: استشارة مرئية",
    "services.description": "الوصف",
    "services.descriptionPlaceholder": "وصف مختصر للخدمة",
    "services.price": "السعر (د.ج)",
    "services.duration": "المدة (دقائق)",
    "services.cancel": "إلغاء",
    "services.saveChanges": "حفظ التغييرات",

    // File Upload
    "upload.invalidType": "نوع ملف غير صالح. يرجى تحميل ملفات PNG أو JPG فقط.",
    "upload.tooLarge": "الملف كبير جداً. الحد الأقصى للحجم هو 4 ميجابايت.",
    "upload.dragDrop": "اسحب وأفلت أو انقر للتصفح",
    "upload.chooseFile": "اختر ملفاً",
    "upload.limitHint": "يجب أن يكون ملف PNG أو JPG (الحد الأقصى 4 ميجابايت)",

    // Webcam
    "webcam.error": "تعذر الوصول إلى الكاميرا. يرجى التحقق من أذونات الكاميرا في متصفحك.",
    "webcam.tryAgain": "إعادة المحاولة",
    "webcam.initializing": "جاري تشغيل الكاميرا...",
    "webcam.retake": "إعادة التقاط الصورة",
    "webcam.capture": "التقاط الصورة الشخصية",

    // Theme
    "theme.system": "حسب النظام",
    "theme.light": "فاتح",
    "theme.dark": "داكن",
    "theme.off": "إيقاف",
    "theme.on": "تشغيل",

    // Language names
    "lang.en": "English",
    "lang.fr": "Français",
    "lang.ar": "العربية",

    // Common
    "common.loading": "جاري التحميل...",
    "common.error": "حدث خطأ ما",

    // Home
    "home.title": "ابحث عن الخدمة المثالية",
    "home.subtitle": "تصفح دليلنا من الخدمات الموثوقة المقدمة من محترفين.",
    "home.noServices": "لا توجد خدمات.",
    "home.logIn": "تسجيل الدخول",
    "home.signUp": "إنشاء حساب",

    // Login
    "login.title": "مرحباً بعودتك",
    "login.subtitle": "سجّل الدخول إلى حسابك للمتابعة",
    "login.iam": "أنا...",
    "login.serviceProvider": "مقدم خدمة",
    "login.consumer": "مستخدم",
    "login.emailOrPhone": "البريد الإلكتروني",
    "login.emailPlaceholder": "أدخل بريدك الإلكتروني",
    "login.emailRequired": "البريد الإلكتروني مطلوب",
    "login.password": "كلمة المرور",
    "login.passwordPlaceholder": "أدخل كلمة المرور",
    "login.passwordRequired": "كلمة المرور مطلوبة",
    "login.forgotPassword": "نسيت كلمة المرور؟",
    "login.roleRequired": "يرجى تحديد دورك",
    "login.signingIn": "جاري تسجيل الدخول...",
    "login.signIn": "تسجيل الدخول",
    "login.noAccount": "ليس لديك حساب؟",
    "login.signUp": "إنشاء حساب",
    "login.failed": "فشل تسجيل الدخول",
    "login.unexpectedError": "حدث خطأ غير متوقع",

    // Signup
    "signup.createAccount": "إنشاء حسابك",
    "signup.profileDetails": "تفاصيل الملف الشخصي",
    "signup.initialSetup": "إعداد الخدمة الأولي",
    "signup.subtitle1": "انضم إلى قنطرة اليوم للبدء",
    "signup.subtitle2": "أخبر العملاء قليلاً عن نفسك",
    "signup.subtitle3": "دعنا نعرف ماذا تفعل",
    "signup.roleSelect": "أريد التسجيل بصفتي:",
    "signup.fullName": "الاسم الكامل",
    "signup.fullNamePlaceholder": "أدخل اسمك الكامل",
    "signup.termsAgree": "أوافق على",
    "signup.termsLink": "شروط الخدمة",
    "signup.and": "و",
    "signup.privacyLink": "سياسة الخصوصية",
    "signup.roleRequired": "يرجى تحديد دور",
    "signup.fullNameRequired": "الاسم الكامل مطلوب",
    "signup.termsRequired": "يجب عليك الموافقة على الشروط والأحكام",
    "signup.processing": "جاري المعالجة...",
    "signup.completeSignUp": "إتمام التسجيل",
    "signup.continue": "متابعة",
    "signup.skip": "تخطي الآن",
    "signup.skipAndFinish": "تخطي وإنهاء",
    "signup.proTitle": "المسمى المهني",
    "signup.proTitlePlaceholder": "مثال: طبيب عائلة",
    "signup.phone": "رقم هاتف الاتصال",
    "signup.bio": "نبذة عنك (السيرة الذاتية)",
    "signup.bioPlaceholder": "أخبر العملاء عن خبرتك...",
    "signup.serviceName": "اسم الخدمة الأولي",
    "signup.serviceNamePlaceholder": "مثال: فحص شامل",
    "signup.servicePrice": "السعر الأساسي (د.ج)",
    "signup.emailVerified": "تم التحقق من البريد الإلكتروني!",
    "signup.redirecting": "جاري التحويل لصفحة تسجيل الدخول...",
    "signup.enterCode": "أدخل رمز التحقق",
    "signup.codeSentTo": "أرسلنا رمزاً مكوناً من 6 أرقام إلى",
    "signup.enterFullCode": "يرجى إدخال رمز التحقق المكون من 6 أرقام كاملاً",
    "signup.verifying": "جاري التحقق...",
    "signup.verifyEmail": "التحقق من البريد",
    "signup.resendCode": "إعادة إرسال الرمز",
    "signup.resendCodeIn": "إعادة إرسال الرمز خلال",
    "signup.resendFailed": "فشل إعادة إرسال الرمز",
    "signup.subtitle": "استفد من أفضل مقدمي الخدمات واكتشف ما يناسبك",
    "signup.username": "اسم المستخدم",
    "signup.usernamePlaceholder": "أدخل اسم المستخدم",
    "signup.usernameRequired": "اسم المستخدم مطلوب",
    "signup.emailOrPhone": "البريد الإلكتروني",
    "signup.emailPlaceholder": "أدخل بريدك الإلكتروني",
    "signup.emailRequired": "البريد الإلكتروني مطلوب",
    "signup.emailInvalid": "يرجى إدخال بريد إلكتروني صحيح",
    "signup.password": "كلمة المرور",
    "signup.passwordPlaceholder": "أنشئ كلمة مرور",
    "signup.passwordRequired": "كلمة المرور مطلوبة",
    "signup.passwordTooShort": "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
    "signup.confirmPassword": "تأكيد كلمة المرور",
    "signup.confirmPasswordPlaceholder": "أعد إدخال كلمة المرور",
    "signup.passwordsNoMatch": "كلمتا المرور غير متطابقتين",
    "signup.creatingAccount": "جاري إنشاء الحساب...",
    "signup.signUp": "إنشاء حساب",
    "signup.haveAccount": "لديك حساب بالفعل؟",
    "signup.signIn": "تسجيل الدخول",
    "signup.failed": "فشل التسجيل",
    "signup.unexpectedError": "حدث خطأ غير متوقع",

    // Provider details extras
    "provider.servicesOffered": "الخدمات المقدمة",
    "provider.noServices": "لا توجد خدمات مدرجة.",
    "provider.contactDetails": "سجّل الدخول لعرض بيانات الاتصال",
    "provider.selectServiceToReview": "اختر خدمة للتقييم...",
    "provider.noServicesToReview": "لا توجد خدمات لدى هذا المزود حالياً للتقييم.",
    "provider.logInToReview": "سجّل الدخول لترك تقييم.",

    // Modern layout redesign translations
    "nav.becomeProvider": "كن مزوداً",
    "nav.installApp": "تثبيت التطبيق",
    "nav.installHintiOS": "للتثبيت، اضغط على مشاركة ثم 'إضافة إلى الشاشة الرئيسية'.",
    "hero.title": "جد أفضل المهنيين في الجزائر",
    "hero.subtitle": "مهن منظمة، حرفيون، مقاولون ذاتيون — موثقون ومتوفرون الآن.",
    "hero.searchPlaceholder": "ما هي الخدمة التي تبحث عنها؟",
    "hero.popular": "شائع:",
    "trust.verified": "+500 مهني موثق",
    "trust.satisfied": "+10,000 عميل سعيد",
    "trust.aiVerification": "التحقق من الشهادات بالذكاء الاصطناعي",
    "trust.authentic": "ملفات شخصية حقيقية 100%",
    "provider.from": "ابتداءً من",
    "provider.contact": "اتصل",
    "provider.getQuote": "احصل على عرض سعر",
    "provider.responseTime": "يستجيب في أقل من ساعتين",
    "provider.memberSince": "عضو منذ",
    "provider.languages": "اللغات",
    "provider.location": "الموقع",
    "footer.categories": "الفئات",
    "footer.about": "حول",
    "footer.support": "الدعم",
    "footer.legal": "قانوني",
    "footer.social": "تواصل معنا",
    "footer.rightsReserved": "جميع الحقوق محفوظة.",

    // Consumer Profile & Notifications
    "notifications.title": "الإشعارات",
    "notifications.emptyTitle": "أنت على إطلاع بكل جديد!",
    "notifications.emptyDesc": "لا توجد إشعارات جديدة. سنعلمك عند وجود أي تحديث.",
    "notifications.browse": "تصفح مقدمي الخدمات",
    "profile.title": "الملف الشخصي",
    "profile.guest": "مستخدم زائر",
    "profile.signInHint": "سجل الدخول للوصول إلى ملفك الشخصي",
    "profile.edit": "تعديل",
    "profile.menu.favorites": "المفضلة",
    "profile.menu.favoritesDesc": "مقدمو الخدمات الذين قمت بحفظهم",
    "profile.menu.payments": "وسائل الدفع",
    "profile.menu.paymentsDesc": "إدارة خيارات الدفع الخاصة بك",
    "profile.menu.notifications": "إعدادات الإشعارات",
    "profile.menu.notificationsDesc": "تخصيص التنبيهات الخاصة بك",
    "profile.menu.support": "المساعدة والدعم",
    "profile.menu.supportDesc": "الأسئلة الشائعة والاتصال بالدعم",
    "profile.signOut": "تسجيل الخروج",

    // Provider Verification & Profile completion
    "verify.banner.pending.title": "التحقق في انتظار المراجعة",
    "verify.banner.pending.msg": "لقد تلقينا مستنداتك بنجاح! قامت Gemini AI بالتدقيق المسبق لمطابقة وجهك واسمك. سيقوم المسؤول بالمراجعة اليدوية النهائية قريباً.",
    "verify.banner.rejected.title": "تم رفض التحقق",
    "verify.banner.rejected.msg": "تم رفض مستندات التحقق الخاصة بك. يرجى إعادة التقديم.",
    "verify.banner.pendingVerif.title": "الحساب في انتظار التحقق",
    "verify.banner.pendingVerif.msg": "أكمل التحقق عن طريق تحميل بطاقة الهوية الحكومية، وصورة شخصية حية، والشهادة المهنية لتفعيل ملفك الشخصي.",
    "verify.resubmitBtn": "إعادة تقديم مستندات التحقق",
    "verify.startBtn": "بدء عملية التحقق",
    "verify.identity.title": "التحقق من الهوية",
    "verify.identity.desc": "تحقق من هويتك باستخدام Didit IDV أو عن طريق تحميل بطاقة الهوية والتقاط صورة شخصية يدويًا.",
    "verify.identity.status": "حالة الهوية",
    "verify.professional.title": "الوثائق المهنية",
    "verify.professional.desc": "قم بتحميل بطاقتك المهنية (بطاقة حرفي، بطاقة مقاول ذاتي، إلخ...) للتحقق من مؤهلاتك.",
    "verify.professional.status": "الحالة المهنية",
    "verify.activity.other": "آخر (نشاط مخصص)",
    "verify.activity.customLabel": "اسم النشاط المخصص",
    "verify.activity.customPlaceholder": "أدخل نشاطك المهني",
    "verify.identity.startBtn": "التحقق من الهوية",
    "verify.professional.startBtn": "التحقق من الوثائق",
    "verify.manual.title": "التحقق يدويًا",
    "verify.manual.idLabel": "تحميل بطاقة الهوية / جواز السفر",
    "verify.manual.selfieLabel": "تحميل الصورة الشخصية",
    "verify.dialog.title": "بدء عملية التحقق من الهوية والمؤهلات",
    "verify.dialog.step": "الخطوة {step} من 3: {name}",
    "verify.step.category": "الفئة المهنية",
    "verify.step.yoti": "الهوية والصورة الشخصية (Didit)",
    "verify.step.credentials": "المؤهلات المهنية",
    "verify.step2.prompt.yoti": "يرجى إتمام التحقق من الهوية والتقاط الصورة الشخصية الحية أدناه باستخدام Didit IDV.",
    "verify.category.prompt": "حدد فئتك المهنية وأدخل تفاصيل التسجيل الرسمية الخاصة بك.",
    "verify.cat.regulated.desc": "أطباء، صيادلة، محامون، موثقون... التحقق من خلال نقابتك المهنية.",
    "verify.cat.artisan.desc": "كهربائيون، سباكون، نجارون، حلاقون... التحقق عبر بطاقة الحرفي CNAM.",
    "verify.cat.auto.desc": "مطورون، مصممون، مسوقون... التحقق عبر بطاقة المقاول الذاتي ANAE.",
    "verify.regulatory.label": "الهيئة / النقابة المهنية الخاصة بك",
    "verify.regulatory.placeholder": "اختر النقابة المهنية",
    "verify.regulatory.group": "مجالس النقابة",
    "verify.license.label": "رقم التسجيل في سجل النقابة",
    "verify.license.placeholder": "مثال: 12345/2020 أو DOC-12345",
    "verify.trade.label": "حرفتك / مهنتك",
    "verify.trade.placeholder": "اختر حرفتك",
    "verify.cnam.label": "رقم بطاقة الحرفي CNAM",
    "verify.cnam.placeholder": "مثال: 16-123456-20",
    "verify.activity.label": "نشاطك الرئيسي",
    "verify.activity.placeholder": "اختر نشاطك",
    "verify.anae.label": "رقم بطاقة المقاول الذاتي ANAE",
    "verify.anae.placeholder": "مثال: AE-123456-2024",
    "verify.secondary.label": "الأنشطة الثانوية (اختياري)",
    "verify.secondary.placeholder": "مثال: استشارات، تدريب...",
    "verify.secondary.addBtn": "إضافة نشاط ثانوي",
    "verify.next.id": "التالي: تحميل الهوية الحكومية",
    "verify.step2.prompt": "يرجى تحميل نسخة مسح ضوئي أو صورة واضحة لبطاقة الهوية الحكومية الرسمية، أو جواز السفر، أو رخصة القيادة.",
    "verify.step2.uploadLabel": "تحميل بطاقة الهوية أو جواز السفر",
    "verify.back": "رجوع",
    "verify.next.selfie": "التالي: التقاط صورة شخصية حية",
    "verify.step3.prompt": "ضع وجهك داخل منطقة الكاميرا والتقط صورة. يضمن هذا التقاط الصورة الشخصية مباشرة بواسطة الكاميرا ويساعد في التحقق من ملكيتك للهوية المرفوعة.",
    "verify.next.docs": "التالي: تحميل بطاقة / شهادة الفئة",
    "verify.step4.prompt": "قم بتحميل نسخة مسح ضوئي لبطاقتك المهنية الرسمية أو مستند الشهادة المطابق لفئتك.",
    "verify.step4.uploadReg": "تحميل شهادة النقابة",
    "verify.step4.uploadArt": "تحميل بطاقة الحرفي CNAM (الوجهان)",
    "verify.step4.uploadAuto": "تحميل بطاقة المقاول الذاتي ANAE (الوجهان)",
    "verify.audit.running": "تقوم Gemini بإجراء عمليات تدقيق تلقائية لمطابقة الوجه والاسم...",
    "verify.submitBtn": "إرسال إلى لوحة التحكم",
    "verify.audit.analyzing": "تحليل التدقيق...",
    "verify.audit.success": "تم استلام الطلب بنجاح!",
    "verify.audit.desc": "أكملت Gemini بنجاح عمليات التحقق التلقائية المسبقة. إليك النتائج المحفوظة في سجلات مراجعة المسؤول:",
    "verify.audit.faceOk": "فحص الوجه: الوجه يطابق بطاقة الهوية الرسمية",
    "verify.audit.faceFail": "فحص الوجه: أشار الذكاء الاصطناعي إلى عدم مطابقة محتملة",
    "verify.audit.nameOk": "فحص الاسم: اسم حامل البطاقة يطابق بطاقة الهوية",
    "verify.audit.nameFail": "فحص الاسم: أشار الذكاء الاصطناعي إلى وجود اختلاف محتمل في الاسم",
    "verify.audit.adminHint": "سيقوم المسؤول بالتحقق من هذه النتائج وتفعيل ملفك الشخصي في غضون 1-2 يوم عمل.",
    "wizard.step": "الخطوة {step} من 3: {name}",
    "wizard.step.basic": "معلومات أساسية",
    "wizard.step.services": "إعداد الخدمات",
    "wizard.step.portfolio": "معرض الأعمال",
    "wizard.photo": "صورة الملف الشخصي",
    "wizard.location": "الموقع (الولاية)",
    "wizard.locationPlaceholder": "اختر ولايتك",
    "wizard.category": "الفئة",
    "wizard.categoryHint": "يتم تحديد فئتك المهنية من خلال مستندات التحقق الخاصة بك ولا يمكن تعديلها.",
    "wizard.bio": "نبذتك الشخصية / عني",
    "wizard.bioPlaceholder": "أخبر العملاء عن خبرتك وكفاءتك...",
    "wizard.saveNext": "حفظ والتالي: الخدمات",
    "wizard.step2.desc": "أضف الخدمات التي تقدمها، بما في ذلك السعر والمدة المتوقعة.",
    "wizard.service.placeholder": "اسم الخدمة (مثال: إصلاح السباكة)",
    "wizard.price.placeholder": "السعر",
    "wizard.duration.placeholder": "المدة",
    "wizard.addService": "+ إضافة خدمة",
    "wizard.back": "رجوع",
    "wizard.saveNextPortfolio": "حفظ والتالي: معرض الأعمال",
    "wizard.step3.desc": "قم بتحميل صور لأعمالك السابقة لتظهر للعملاء ما يمكنك القيام به. أضف روابط الصور أدناه: (مثال: https://imgur.com/your-image.jpg)",
    "wizard.imgUrl.placeholder": "رابط الصورة",
    "wizard.emptyPortfolio": "لم يتم إضافة صور لمعرض الأعمال بعد. يمكنك تخطي هذه الخطوة وإضافتها لاحقاً.",
    "wizard.addPortfolioImg": "+ إضافة صورة لمعرض الأعمال",
    "wizard.readyTitle": "جاهز للانطلاق!",
    "wizard.readyDesc": "من خلال التفعيل، سيكون ملفك الشخصي مرئياً بشكل عام لجميع العملاء الذين يبحثون عن خدماتك.",
    "wizard.saving": "جاري الحفظ...",
    "wizard.goPublic": "انطلق مباشرة",
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("en")

  useEffect(() => {
    const saved = localStorage.getItem("locale") as Locale
    if (saved && translations[saved]) {
      setLocaleState(saved)
    }
  }, [])

  const setLocale = (newLocale: Locale) => {
    setLocaleState(newLocale)
    localStorage.setItem("locale", newLocale)
    document.documentElement.lang = newLocale
    document.documentElement.dir = newLocale === "ar" ? "rtl" : "ltr"
  }

  // Apply on mount
  useEffect(() => {
    document.documentElement.lang = locale
    document.documentElement.dir = locale === "ar" ? "rtl" : "ltr"
  }, [locale])

  const t = (key: string): string => {
    return translations[locale]?.[key] || translations.en[key] || key
  }

  const dir = locale === "ar" ? "rtl" : "ltr"

  const formatNumber = (n: number): string => {
    if (locale === "ar") {
      return new Intl.NumberFormat("ar-DZ").format(n)
    }
    return new Intl.NumberFormat(locale === "fr" ? "fr-DZ" : "en").format(n)
  }

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t, dir, formatNumber }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
